---
abstract: 'Temporary changing working directory (chdir)'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.6, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cwd-Guard
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Cwd::Guard:
    file: lib/Cwd/Guard.pm
    version: 0.04
requires:
  Cwd: 0
  Exporter: 0
  if: 0
  parent: 0
resources:
  bugtracker: https://github.com/kazeburo/Cwd-Guard/issues
  homepage: https://github.com/kazeburo/Cwd-Guard
  repository: git://github.com/kazeburo/Cwd-Guard.git
version: 0.04
x_contributors:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
