--- #YAML:1.0
name:               Sub-Identify
version:            0.12
abstract:           Retrieve names of code references
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
resources:
    repository:
        type:  git
        url:   https://github.com/rgs/Sub-Identify.git
        web:   https://github.com/rgs/Sub-Identify
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  2
