---
abstract: 'Override subroutines in a module for unit testing'
author:
  - 'Current Maintainer: Geoff Franks <gfranks@cpan.org>'
  - 'Original Author: Simon Flack <simonflk _AT_ cpan.org>'
build_requires:
  Test::More: '0.45'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.150001'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-MockModule
provides:
  Test::MockModule:
    file: lib/Test/MockModule.pm
    version: '0.10'
requires:
  Carp: '0'
  SUPER: '0'
  Scalar::Util: '0'
resources:
  bugtracker: https://github.com/geofffranks/test-mockmodule/issues
  homepage: https://github.com/geofffranks/test-mockmodule
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: git://github.com/geofffranks/test-mockmodule.git
version: '0.10'
