---
abstract: ~
author:
  - 'Tim Jenkins <tim@sendgrid.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Class::Load: 0
  Test::MockModule: 0
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SendGrid
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Encode: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  MIME::Entity: 0
  Mail::Address: 0
  Net::SMTP::TLS: 0
  Sys::Hostname: 0
  URI::Escape: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: '1.3'
